import sys
from libs import test_framework as t_fwork
sys.path.append('../')

"""
@UTHOR: AKSHAY NEHE
Q. Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""


def get_even_fib_sum(n):
    f1 = 1
    f2 = 1
    result_sum = 0
    while True:
        if f2 % 2 == 0:
            result_sum += f2
        # print(f2)
        f2 += f1
        if f2 > n:
            break
        f1 = f2 - f1
    return result_sum


print('Solution for n = 4 mil -> {0}'.format(get_even_fib_sum(4000000)))

print('** Running Tests now **')
tests = t_fwork.CustomTests()
# 1 1 2 3 5
tests.run_test(get_even_fib_sum, 2, 6)

# 1 1 2 3 5 8
tests.run_test(get_even_fib_sum, 10, 8)

# 1 1 2 3 5 8 13
tests.run_test(get_even_fib_sum, 10, 20)

# 1 1 2 3 5 8 13 21
tests.run_test(get_even_fib_sum, 44, 25)
